# Generated by Django 5.0.4 on 2024-04-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_address_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="zip",
            field=models.CharField(default="-", max_length=8),
        ),
    ]
