# Generated by Django 5.0.4 on 2024-04-24 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_auto_20240423_1441"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="Featued_product",
            new_name="featued_product_id",
        ),
    ]
