# Generated by Django 5.0.4 on 2024-04-24 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_rename_featued_product_collection_featued_product_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="featued_product_id",
            new_name="featured_product",
        ),
    ]
